name: GrimurOTT
main: nl.thedutchmc.dutchytpa.Tpa
version: 1.1.2
api-version: 1.16
author: Kali
description: A one-time teleport plugin, based on DutchyTPA by TheDutchMC.

commands:
 ott:
  description: OTT to a player
 ottaccept:
  description: Accept a OTT request
 ottdeny:
  description: Deny a OTT request
 ottyes:
  description: Alias for /ottaccept
 ottno:
  description: Alias for /ottdeny